### ISSUE TITLE
[Question] Does it use ytmusicapi?

### ISSUE THREAD

**Issue by JeffThorns** [arma7x/kaimusic#16]
i was wondering if the app uses the [api ](https://github.com/sigma67/ytmusicapi),  the app idea has so much potential, maybe can this api help

**Comment by arma7x** [comment]
~~No. [ytmusicap](https://github.com/sigma67/ytmusicapi) require a python server while YT-Music communicate directly with YouTube server(except the process of extracting songs from playlist id) and stream the audio from invidious instance~~

This app only play local audio files. For youtube music, please open the issue here https://github.com/arma7x/kai-yt-music/issues
